server:
  port: 9093

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_dang?
      useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 121223
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  mvc:
    async:
      request-timeout: 30000


mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.waiterxiaoyy.backandroiddesign
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
